[project]
name = "jguides_2024"
authors = [{ name = "Jen Guidera"}]
version = "0.0.1"
dependencies = [
  "spyglass-neuro",
  "statannotations"
]

[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
where = ["src"]
